#!/usr/bin/env node
/**
 * Individual local setup — no cloud credentials.
 * Creates ~/.focusspace and writes .env.local (local mode) if missing.
 *
 * Usage (from a FocusSpace checkout):
 *   node skills/focusspace/scripts/setup-local.mjs
 *   node skills/focusspace/scripts/setup-local.mjs /path/to/focusspace
 */
import { existsSync, mkdirSync, readFileSync, appendFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const LOCAL_ENV = [
  "FOCUSSPACE_MODE=local",
  "NEXT_PUBLIC_FOCUSSPACE_MODE=local",
  "NEXT_PUBLIC_SITE_URL=http://localhost:3000",
].join("\n") + "\n";

function isFocusSpaceRepo(dir) {
  try {
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
    return pkg.name === "focusspace";
  } catch {
    return false;
  }
}

function findRepo(explicit) {
  if (explicit) {
    const abs = resolve(explicit);
    return isFocusSpaceRepo(abs) ? abs : null;
  }
  if (isFocusSpaceRepo(process.cwd())) return process.cwd();
  const here = dirname(fileURLToPath(import.meta.url));
  // skills/focusspace/scripts → repo root
  const fromSkill = resolve(here, "../../..");
  return isFocusSpaceRepo(fromSkill) ? fromSkill : null;
}

const dataDir = join(homedir(), ".focusspace");
mkdirSync(dataDir, { recursive: true });
console.log(`data dir  ${dataDir}`);
console.log(`database  ${join(dataDir, "focusspace.db")}  (created on first boot)`);

const repo = findRepo(process.argv[2]);
if (!repo) {
  console.log("");
  console.log("No FocusSpace checkout found.");
  console.log("Clone https://github.com/EntangledQuantum/focusspace then re-run from that directory.");
  console.log("");
  console.log("Next:");
  console.log("  git clone https://github.com/EntangledQuantum/focusspace.git");
  console.log("  cd focusspace");
  console.log("  node skills/focusspace/scripts/setup-local.mjs");
  process.exit(0);
}

const envPath = join(repo, ".env.local");
if (!existsSync(envPath)) {
  writeFileSync(envPath, `# Generated by skills/focusspace/scripts/setup-local.mjs — do not commit\n${LOCAL_ENV}`);
  console.log(`wrote     ${envPath}`);
} else {
  const existing = readFileSync(envPath, "utf8");
  const missing = [];
  if (!/^FOCUSSPACE_MODE=/m.test(existing)) missing.push("FOCUSSPACE_MODE=local");
  if (!/^NEXT_PUBLIC_FOCUSSPACE_MODE=/m.test(existing)) missing.push("NEXT_PUBLIC_FOCUSSPACE_MODE=local");
  if (missing.length) {
    const prefix = existing.endsWith("\n") ? "" : "\n";
    appendFileSync(envPath, `${prefix}# appended by setup-local.mjs\n${missing.join("\n")}\n`);
    console.log(`updated   ${envPath} (${missing.join(", ")})`);
  } else {
    console.log(`kept      ${envPath}`);
  }
}

console.log("");
console.log("Next:");
console.log("  npm install");
console.log("  npm run dev");
console.log("  open http://127.0.0.1:3000 and click Open FocusSpace");
console.log("");
console.log("MCP (after the app is up):");
console.log("  HTTP   http://127.0.0.1:3000/api/mcp");
console.log("  stdio  npx tsx scripts/mcp-stdio.ts");
console.log("");
console.log("If Node is older than 20, use Docker instead: docker compose up --build");
