#!/usr/bin/env node
/**
 * Interactive setup — writes .env.local with Supabase credentials.
 * Usage: node scripts/setup-env.mjs
 */
import { createInterface } from "readline";
import { writeFileSync } from "fs";

const rl = createInterface({ input: process.stdin, output: process.stdout });
const q = (prompt) => new Promise((res) => rl.question(prompt, res));

console.log("\n🔧  FocusSpace — Environment Setup\n");

const url    = await q("Supabase Project URL         : ");
const anon   = await q("Supabase Anon (Public) Key   : ");
const service = await q("Supabase Service Role Key    : ");
const siteUrl = await q("Site URL (e.g. http://localhost:3000) : ");

rl.close();

const env = `# Generated by scripts/setup-env.mjs — do not commit
NEXT_PUBLIC_SUPABASE_URL=${url.trim()}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon.trim()}
SUPABASE_SERVICE_ROLE_KEY=${service.trim()}
NEXT_PUBLIC_SITE_URL=${siteUrl.trim()}
`;

writeFileSync(".env.local", env);
console.log("\n✅  .env.local written.\n");
console.log("Next steps:");
console.log("  1. npm run dev");
console.log("  2. Open http://localhost:3000\n");
